"""
RLiable comparison for Level 1: DQN vs RND-DQN.

This script reads the CSV generated by plot_l1_rnd_dqn_comparison.py.
It creates:
1. An RLiable IQM sample-efficiency curve.
2. A CSV file with final IQM / mean / median estimates and confidence intervals.

"""

from typing import Dict, List

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from rliable import metrics
from rliable.library import get_interval_estimates
from rliable.plot_utils import plot_sample_efficiency_curve

RESULTS_DIR = Path("rl_exercises/week_7/results_l1")
CSV_PATH = RESULTS_DIR / "l1_rnd_dqn_results.csv"

OUTPUT_CURVE = RESULTS_DIR / "l1_rliable_iqm_curve.png"
OUTPUT_STATS = RESULTS_DIR / "l1_rliable_final_stats.csv"


def moving_average(values: np.ndarray, window: int = 10) -> np.ndarray:
    """Smooth episode returns with a simple moving average."""
    if len(values) < window:
        return values

    kernel = np.ones(window) / window
    return np.convolve(values, kernel, mode="valid")


def build_score_arrays(
    df: pd.DataFrame,
    num_eval_points: int = 100,
    smoothing_window: int = 10,
) -> tuple[np.ndarray, Dict[str, np.ndarray]]:
    """
    Convert variable-length episode data into fixed-length score arrays.

    RLiable expects arrays with shape:
        (num_seeds, num_eval_points)

    Since each seed can finish a different number of episodes, we interpolate the
    smoothed episode returns onto a shared frame grid.
    """
    max_common_frame = int(df.groupby(["algorithm", "seed"])["frame"].max().min())
    eval_frames = np.linspace(1, max_common_frame, num_eval_points)

    train_scores: Dict[str, List[np.ndarray]] = {}

    for algorithm in sorted(df["algorithm"].unique()):
        train_scores[algorithm] = []

        algo_df = df[df["algorithm"] == algorithm]

        for seed in sorted(algo_df["seed"].unique()):
            seed_df = algo_df[algo_df["seed"] == seed].sort_values("frame")

            frames = seed_df["frame"].to_numpy(dtype=np.float32)
            returns = seed_df["episode_return_ext"].to_numpy(dtype=np.float32)

            smoothed_returns = moving_average(returns, window=smoothing_window)

            if len(returns) >= smoothing_window:
                smoothed_frames = frames[smoothing_window - 1 :]
            else:
                smoothed_frames = frames

            interpolated_returns = np.interp(
                eval_frames,
                smoothed_frames,
                smoothed_returns,
                left=smoothed_returns[0],
                right=smoothed_returns[-1],
            )

            train_scores[algorithm].append(interpolated_returns)

        train_scores[algorithm] = np.array(train_scores[algorithm], dtype=np.float32)

    return eval_frames, train_scores


def plot_iqm_curve(
    eval_frames: np.ndarray, train_scores: Dict[str, np.ndarray]
) -> None:
    """
    Plot IQM sample-efficiency curves with confidence intervals using RLiable.
    """
    iqm = lambda scores: np.array(  # noqa: E731
        [
            metrics.aggregate_iqm(scores[:, eval_idx])
            for eval_idx in range(scores.shape[-1])
        ]
    )

    iqm_scores, iqm_cis = get_interval_estimates(
        train_scores,
        iqm,
        reps=2000,
    )

    _ = plot_sample_efficiency_curve(
        eval_frames,
        iqm_scores,
        iqm_cis,
        algorithms=sorted(train_scores.keys()),
        xlabel="Environment frames",
        ylabel="IQM extrinsic episode return",
    )

    plt.title("RLiable IQM curve: DQN vs RND-DQN on CartPole-v1")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUTPUT_CURVE, dpi=200)
    plt.close()

    print(f"Saved RLiable IQM curve to: {OUTPUT_CURVE}")


def save_final_statistics(train_scores: Dict[str, np.ndarray]) -> None:
    """
    Compute final aggregate statistics with RLiable and save them as CSV.

    We use the final evaluation point of each seed.
    """
    final_scores = {
        algorithm: scores[:, -1:] for algorithm, scores in train_scores.items()
    }

    aggregate_func = lambda scores: np.array(  # noqa: E731
        [
            metrics.aggregate_iqm(scores),
            metrics.aggregate_mean(scores),
            metrics.aggregate_median(scores),
        ]
    )

    point_estimates, interval_estimates = get_interval_estimates(
        final_scores,
        aggregate_func,
        reps=2000,
    )

    rows = []

    metric_names = ["IQM", "Mean", "Median"]

    for algorithm in sorted(final_scores.keys()):
        estimates = np.asarray(point_estimates[algorithm])
        intervals = np.asarray(interval_estimates[algorithm])

        for metric_idx, metric_name in enumerate(metric_names):
            rows.append(
                {
                    "algorithm": algorithm,
                    "metric": metric_name,
                    "estimate": float(estimates[metric_idx]),
                    "ci_lower": float(intervals[0, metric_idx]),
                    "ci_upper": float(intervals[1, metric_idx]),
                }
            )

    stats_df = pd.DataFrame(rows)
    stats_df.to_csv(OUTPUT_STATS, index=False)

    print(f"Saved RLiable final statistics to: {OUTPUT_STATS}")
    print(stats_df)


def main() -> None:
    df = pd.read_csv(CSV_PATH)

    eval_frames, train_scores = build_score_arrays(df)

    plot_iqm_curve(eval_frames, train_scores)
    save_final_statistics(train_scores)


if __name__ == "__main__":
    main()
